name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend to Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      working-directory: backend
      run: npm install

    - name: Run Tests
      working-directory: backend
      run: npm test

    - name: Zip Backend Files
      working-directory: backend
      run: zip -r backend.zip .

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION
        aws elasticbeanstalk create-application-version \
          --application-name "YourApplicationName" \
          --version-label "v-${{ github.run_number }}" \
          --source-bundle S3Bucket="YourBucketName",S3Key="backend.zip"
        aws elasticbeanstalk update-environment \
          --application-name "YourApplicationName" \
          --environment-name "YourEnvironmentName" \
          --version-label "v-${{ github.run_number }}"